FROM devhub.yintaerp.com/yintatech/ops-node-python-allure:3.0.0
RUN rm -f /etc/localtime && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ADD ./test_platform /opt/test_platform
RUN pip install -r /opt/test_platform/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
RUN cp /opt/test_platform/static/import_test_platform.pth /usr/local/lib/python3.8/site-packages/import_test_platform.pth
RUN rm -f /usr/local/lib/python3.8/site-packages/django/db/backends/mysql/operations.py && cp /opt/test_platform/static/operations.py /usr/local/lib/python3.8/site-packages/django/db/backends/mysql/
RUN rm -f /usr/local/lib/python3.8/site-packages/django_apscheduler/jobstores.py && cp /opt/test_platform/static/jobstores.py /usr/local/lib/python3.8/site-packages/django_apscheduler/
